### ISSUE TITLE
0;31madb is not in your $PATH

### ISSUE THREAD

**Issue by xanderres** [kosborn/p2p-adb#10]
when i try to launch it on my xperia x8

CyanogenMod installed
BusyBox installed
Rooted
Android 2.3.7

 $ su
 # cd sdcard/p2p-adb
 # sh ./run.sh
 version: not found
 \033[0;31madb is not in your $PATH
 Add it to $PATH, or enabel $tryStaticADB in run.sh \033[om

What does that mean ?     What do I have to do ?

**Comment by PaulMcMillan** [comment]
It sounds like you have colors turned on in your terminal. Try disabling them...

**Comment by xanderres** [comment]
the same error

**Comment by kosborn** [comment]
Weird. I guess I'll go ahead and add the option to disable colors (but personally I think it assists more easily reading the terminal on such a small device, and plan to build it out a little more.)

Which version of Cyanogenmod? Do you have adb in $PATH? (I'm guessing not.)

**Comment by xanderres** [comment]
how do i get adb in $PATH?

**Comment by kosborn** [comment]
@xanderres Apologies for the late response, I noticed you closed it, so I hope you were able to fix it.

The current version has an option to attempt to use a statically compiled ADB binary, but only on mobile devices (specifically ARM devices). You can enable this by modifying run.sh (line 19).
