### ISSUE TITLE
noob

### ISSUE THREAD

**Issue by spykid12** [kosborn/p2p-adb#16]
this is one of the awesome thing i saw..i watched  all your videos from Hak5 from youtube fom whereever i can find this topic of your...

ok I am really noob at this and have no clue what to do or where to get stared

I have samsung s2 and i would like to make use of this p2p-adb..so what should i do ?
like where do i copy all this files ? do i have to root my phone ? do i have to run some custom rom on my phone ?

i got the OTG cable 

thanks a lot

**Comment by ghost** [comment]
Rooting your phone wont brick it, but flashing custom rom does. Anyways download The drivers if you need Them For your pc to Recognize your phone. If Not Just Plug it in and see if it shows up when you plug it in. If so, just Move The folder to root of your phone then use Terminal emulator to execute it.

**Comment by spykid12** [comment]
how do i execute ? and which is the root folder. Is it phones internal memory?

**Comment by ghost** [comment]
sorry for not responding when you go to plug you phone it just drag and drop the folder to the root directory and just browse to it with terminal emulator.

**Comment by ghost** [comment]
when you cd to that directory (in terminal emulator) you type su to give you root privileges then you type sh ./run.sh

**Comment by spykid12** [comment]
no problem man
sorry when i try cd into folder i can open all the folders but this one
it says no such directory or file found? 
can you add me on some type of messenger or something where we can chat ?

**Comment by ghost** [comment]
skype: demonjesterhf

**Comment by spykid12** [comment]
added you

**Comment by sibo2540** [comment]
Any one help im a noob n cant figure this out how do i get it to run 
Any help would b much appreciated

**Comment by ghost** [comment]
sibo add me on skype demonjesterhf and I can help you
