### ISSUE TITLE
 Unknown option -S 

### ISSUE THREAD

**Issue by Hackrylix** [kosborn/p2p-adb#2]
Hi,

Just tested your tool : awesome !

 A little bug came up, just to report it and give you feedback :

Info : HTC Wildfire S CM7 
(I found a way to know if someone tried to install the app : the Link2SD log ^^)
# 
# output :

Choose wisely: 6
Unlocking Screen
395 KB/s (16580 bytes in 0.040s)
    pkg: /data/local/tmp/AntiGuard.apk
Success
Error: Unknown option: -S
usage: am [subcommand] [options]

```
start an Activity: am start [-D] [-W] <INTENT>
    -D: enable debugging
    -W: wait for launch to complete

start a Service: am startservice <INTENT>

send a broadcast Intent: am broadcast <INTENT>

start an Instrumentation: am instrument [flags] <COMPONENT>
    -r: print raw results (otherwise decode REPORT_KEY_STREAMRESULT)
    -e <NAME> <VALUE>: set argument <NAME> to <VALUE>
    -p <FILE>: write profiling data to <FILE>
    -w: wait for instrumentation to finish before returning

start profiling: am profile <PROCESS> start <FILE>
stop profiling: am profile <PROCESS> stop

start monitoring: am monitor [--gdb <port>]
    --gdb: start gdbserv on the given port at crash/ANR

<INTENT> specifications include these flags:
    [-a <ACTION>] [-d <DATA_URI>] [-t <MIME_TYPE>]
    [-c <CATEGORY> [-c <CATEGORY>] ...]
    [-e|--es <EXTRA_KEY> <EXTRA_STRING_VALUE> ...]
    [--esn <EXTRA_KEY> ...]
    [--ez <EXTRA_KEY> <EXTRA_BOOLEAN_VALUE> ...]
    [-e|--ei <EXTRA_KEY> <EXTRA_INT_VALUE> ...]
    [-n <COMPONENT>] [-f <FLAGS>]
    [--grant-read-uri-permission] [--grant-write-uri-permission]
    [--debug-log-resolution]
    [--activity-brought-to-front] [--activity-clear-top]
    [--activity-clear-when-task-reset] [--activity-exclude-from-recents]
    [--activity-launched-from-history] [--activity-multiple-task]
    [--activity-no-animation] [--activity-no-history]
    [--activity-no-user-action] [--activity-previous-is-top]
    [--activity-reorder-to-front] [--activity-reset-task-if-needed]
    [--activity-single-top]
    [--receiver-registered-only] [--receiver-replace-pending]
    [<URI>]
```

Starting: null
java.lang.NullPointerException
#

**Comment by darKpoiSon** [comment]
tried a bit around and found a workable solution. I have no idea if there something wrong when using this method but try changing
<code>adb shell am start -S io.kos.antiguard/.unlock</code>
to
<code>adb shell am start -a android.intent.action.MAIN -n io.kos.antiguard/.unlock</code>
in the <b>installAnti.sh</b> Script.

It worked for me..

**Comment by parkour86** [comment]
Thanks, that command worked for me.

**Comment by kosborn** [comment]
@Hackrylix Thanks a lot. I haven't come across that error. I've got a big push that I'll be making in the next few days (for DerbyCon), and will have it fixed.

**Comment by denzuko** [comment]
Kos, this is still in mainline installAnti.sh. Since I'm adding some new commands for different attack vectors (namely pin/passwords, anti-malware disabling, and browser data "recovery"); while I'm at it I'll patch the installAnti.sh script to send along with my push request.
