### ISSUE TITLE
Device Connection

### ISSUE THREAD

**Issue by D4rkz3rO** [kosborn/p2p-adb#20]
First and foremost, Thank you Kos for an awesome idea and bringing it to reality!

I've read all the posts and see that there was an issue where the host couldn't get a connection to the target. I think it was issue 6? Bit it seems i have the same problem and cannot get my devices connected. I may have missed something and hope someone can help.

Problem: Cannot connect to target. 

Code:-----------------------------------------------
su
# cd /sdcard/p2p
# sh ./run.sh

_deamon started successfully. now running ... blah blah_
## Waiting for phone to connect.............

Now when i plug in my target, it starts charging, so connected but nothing on my host.... Any help??

My setup: ADB activated on all devices.
Host (HTC One S)
AOKP JB build 1 -- Rooted -- SU

Target: Galaxy Vibrant 
Cyanogenmod Android 4.04
Rooted and w/ SU

**Comment by ghost** [comment]
@Simster007 tried 

```
adb devices
```

?

**Comment by denzuko** [comment]
Target needs to be in developer mode by default most manufactures set their phones to show up as either a media player or usb charging for the very same reason this pentesting tool exists.

**Comment by bramaal** [comment]
May be it is because of tarveg settings go change default @plugger
