### ISSUE TITLE
Need help installing on phone

### ISSUE THREAD

**Issue by nermolov** [kosborn/p2p-adb#30]
I have a phone with cyanogenmod installed and terminal emulator but I am having trouble getting the scripts to work. If I try to chmod the scripts the terminal gives me a "bad mode" error and it doesnt work. If I chmod ahead of time then I copy the files, it is stripped. Help?

**Comment by denzuko** [comment]
Bad mode means the permissions on the file are not set correctly, and some versions of chmod don't understand the o+rw notation. All implementations of chmod(1) do understand POSIX octal notation, where 0=none, 1=execute, 2=read, 4=write and one would add those numbers to get the flag mask. There is also a series of these bits where the first bit is the file type and is not related to permissions then a set of three for owner permissions, group permissions, and users permissions so try:

```
chmod 0644 ./filename.*
```

and

```
chmod 0755 ./filename.{sh,bin,exe}
```

HTH.

**Comment by nermolov** [comment]
Thank you, this worked
