### ISSUE TITLE
adb is not in your $Path HELP!!

### ISSUE THREAD

**Issue by blacksmith94** [kosborn/p2p-adb#42]
When i run `sh ./run.sh` it says adb is not in your $Path:

<a href='https://postimg.org/image/wfq8p2s3r/' target='_blank'><img src='https://s31.postimg.org/wfq8p2s3r/423912462_121432_15364481392804349163.jpg' border='0' alt='postimage'/></a>

I tried solving it this way -> https://github.com/kosborn/p2p-adb/issues/36
But when i run `find / -name adb` i get this output:

<a href='https://postimg.org/image/tzofb8a13/' target='_blank'><img src='https://s31.postimg.org/tzofb8a13/425228282_31655_8347074348181251129.jpg' border='0' alt='postimage'/></a>

I tried `export PATH=$PATH:/path-to-adb-directory-as-discovered-by-find` as it says in the old issue post with the 3 first routes showing on the image above, but when i try again and run `sh ./run.sh` i get the same error...
I also tried running from /data/p2p-adb but neither work...
Maybe i dont have adb? I dont know... 
help please, i wanna run this framework so bad.

Additional info:

Im using: Nexus 5 with CM13, Android version 6.0.1, I'm using NetHunter and I had BusyBox already installed

**Comment by denzuko** [comment]
Needs android-sdk and android-ndk to be installed. though honestly p2p-adb worked better with older versions of android, ie pre-5.0. Afterall this is a five+ year old root kit and they have patched a lot since then.

**Comment by denzuko** [comment]
Duplicate of #36

**Comment by ghost** [comment]
How to solve adb is not in your path without root please tell me

**Comment by denzuko** [comment]
@BeastF5 maybe one should root their phone?

**Comment by ghost** [comment]
No my device is not rooted how can i run this p2p adb without root

**Comment by jebyjoseph** [comment]
open run.sh with text editor and rename tryStaticADB=1
