### ISSUE TITLE
Won't work on Android 5.0.1 ??

### ISSUE THREAD

**Issue by Aizen-Barbaros** [kosborn/p2p-adb#44]
Please help me why it says that ?
Device unauthorized. Please check the confirmation dialog on your device.
I want to add a screenshot but my english isnt very good and im new here. Thanks
So i decided to copy all the script :
u0_a269@jflte:/ $ cd storage/emulated/0/p2p-adb-master
u0_a269@jflte:/storage/emulated/0/p2p-adb-master $
sh run.sh
Using: /system/bin/adb
Welcome to p2p-adb framework!
Let's break some stuff.
error: device unauthorized. Please check the confirmation dialog on your device.
error: device unauthorized. Please check the confirmation dialog on your device.
Trying to push busybox...
error: device unauthorized. Please check the confirmation dialog on your device.
error: device unauthorized. Please check the confirmation dialog on your device.
What do you want to do today?
        0) Check if root
        1) Steal App data
        2) Steal Google data
        3) Steal Camera Photos
        4) Steal JPGs > 200k
        5) Steal Accounts
        6) Install/Uninstall AntiGuard
        7) Root 4.0-4.1.1 using adb race condition
        (Not guaranteed to work on all devices!)
        8) Get pattern unlock!
        x) Exit

Choose wisely: 3
GRAB DEM PHOTOS
error: device unauthorized. Please check the confirmation dialog on your device.
Camera directory doesn't exist?

error: device unauthorized. Please check the confirmation dialog on your device.
error: device unauthorized. Please check the confirmation dialog on your device.
Trying to push busybox...
error: device unauthorized. Please check the confirmation dialog on your device.
error: device unauthorized. Please check the confirmation dialog on your device.
What do you want to do today?
        0) Check if root
        1) Steal App data
        2) Steal Google data
        3) Steal Camera Photos
        4) Steal JPGs > 200k
        5) Steal Accounts
        6) Install/Uninstall AntiGuard
        7) Root 4.0-4.1.1 using adb race condition
        (Not guaranteed to work on all devices!)
        8) Get pattern unlock!
        x) Exit

Choose wisely: 0
error: device unauthorized. Please check the confirmation dialog on your device.
error: device unauthorized. Please check the confirmation dialog on your device.
WHAT AM I???

error: device unauthorized. Please check the confirmation dialog on your device.
error: device unauthorized. Please check the confirmation dialog on your device.
Trying to push busybox...
error: device unauthorized. Please check the confirmation dialog on your device.
error: device unauthorized. Please check the confirmation dialog on your device.
What do you want to do today?
        0) Check if root
        1) Steal App data
        2) Steal Google data
        3) Steal Camera Photos
        4) Steal JPGs > 200k
        5) Steal Accounts
        6) Install/Uninstall AntiGuard
        7) Root 4.0-4.1.1 using adb race condition
        (Not guaranteed to work on all devices!)
        8) Get pattern unlock!
        x) Exit

Choose wisely: 7
Trying to root...
adb: unable to connect for restore
run.sh: ./root4.x.sh[13]: can't create /data/local/tmp//p2p-tmp: Permission denied
error: device unauthorized. Please check the confirmation dialog on your device.
run.sh: ./root4.x.sh[28]: can't create /data/local/tmp//p2p-tmp: Permission denied
error: device unauthorized. Please check the confirmation dialog on your device.

error: device unauthorized. Please check the confirmation dialog on your device.
error: device unauthorized. Please check the confirmation dialog on your device.
Trying to push busybox...
error: device unauthorized. Please check the confirmation dialog on your device.
error: device unauthorized. Please check the confirmation dialog on your device.
What do you want to do today?
        0) Check if root
        1) Steal App data
        2) Steal Google data
        3) Steal Camera Photos
        4) Steal JPGs > 200k
        5) Steal Accounts
        6) Install/Uninstall AntiGuard
        7) Root 4.0-4.1.1 using adb race condition
        (Not guaranteed to work on all devices!)
        8) Get pattern unlock!
        x) Exit

Choose wisely:

**Comment by Aizen-Barbaros** [comment]
And when i write "adb devices" :
20861027                 unauthorized

**Comment by nemsis72** [comment]
I'm on lollipop 5.1.1 and I'm also getting same error, This also wont launch adb confirmation dialog screen on any device i try to connect.m y adb version is ANDROID DEBUG BRIDGE version 1.0. 32

**Comment by iDPhekt** [comment]
Well first of all folks if you look this project is four years old, and if you look some more and maybe do a little google search, you will find out that it doesnt work because of a little file called ADBsecure. The files only job was to pretty much patch the ability to do any of this without having rooted access to the device beforehand. Even though the purpose of this project probably wasn't to spy on a cheating spouse or any other malicious intentions some people definitely used it for such and its been probably 2-3 years since this worked. Too bad too.

**Comment by nemsis72** [comment]
I can get it to work on my Linux PC.

**Comment by iDPhekt** [comment]
Computer is different it has a built in higher level of permissions, totally a different situation. Adb secure is made to stop adbbover otg.

**Comment by nemsis72** [comment]
Thanks for answering bro.. appreciate it.

**Comment by iDPhekt** [comment]
No problem, the only way for a phone to do it now is to remove adbsecure

**Comment by Aizen-Barbaros** [comment]
Thanks you bro i asked because i m French its a bit difficult for me to understand the english but thanks for answering :)
