### ISSUE TITLE
Why it is not "natively root"?

### ISSUE THREAD

**Issue by patschi** [kosborn/p2p-adb#9]
I tested p2p-adb 2 days ago on my Android tablet and it worked fine, but not the functions which requires root. But my tablet is definility rooted: I have CyanogenMod 9.1 stable installed. But instead of SuperUser I use SuperSU - Is this the reason because it won't detect correctly if it is rooted?

Nice work you have done! :)

**Comment by kosborn** [comment]
"Natively root" means that you're not dropped into root from the instant you connect to adb. I try to alleviate this with the "command" wrapper, which uses a defined variable to decide where or not I need to prepend su -c to the commands.

Can you go into developer settings, and see what's set under "Root Access"? I haven't run into any discrepancies when the "natively root" dialogue is thrown.

**Comment by patschi** [comment]
On my S3 it's just for apps and on my Tablet (where I tried to "hack") have Apps and ADB. Thanks for your response :)
